-- AlterTable
ALTER TABLE `Link` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `User` ADD COLUMN `theme` VARCHAR(191) NOT NULL DEFAULT 'default';
